

services:
  api:
    build: ./backend        # build from Dockerfile in backend folder
    ports:
      - "8000:8000"         # expose port
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - REDIS_URL=${REDIS_URL}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}talk to redis container
   